version: "3.9"
services:
  account:
    build: ./account
    container_name: app-account
    ports:
      - "3002:3002"
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - "3001:3001"
  mongo:
    container_name: mongo-ecomm
    image: mongo
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  mysql:
    image: mysql
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db-mongo-ecomm:
  mysql-ecomm-volume: