version: "3.9"
services:
  account:
    build: ./account
    container_name: app-account
    ports:
      - "3002:3002"
    depends_on:
      - mongo  

  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    container_name: mongo-ecomm
    image: mongo
    volumes:
      - db-mongo-ecomm:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  mysql:
    image: mysql
    volumes:
      - mysql-ecomm-volume:/var/lib/mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

  finance:
    build: ./finance 
    container_name: ecomm-finance
    ports:
      - 3010:3010   
    depends_on:
      - mysql
volumes:
  db-mongo-ecomm:
  mysql-ecomm-volume: