openapi: 3.0.3
info:
  title: API de consulta de produtos
  description: API que vai listar todas as categorias de produtos que do nosso sistemas
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Daniel Maciel Duarte
    email: daniel.duarte@pagonxt.com
  license:
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
servers: 
- url: https://api-test.com/
  description: API de Categorias
paths:
  /api/categories:
    get:
      tags:
       - lista de categorias
      summary: Recupera todas as categorias cadastradas
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoriaslista"
  /api/admin/categories:
    post:
      tags: 
      - inserindo uma nova categoria
      summary: Nova categoria inserida pelo admin 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201: 
          description: Nova categoria criada com sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
      security:
        - auth: []
  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type:
          string
      required: true
    get:
      tags: 
        - Buscando uma categoria pelo id
      summary: Retorna detalhes de uma categoria do respectivo id
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
  /api/admin/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type:
          string
      required: true
    put:
      tags:  
      - atualização de dados (adm)
      summary: Admin atualiza os dados de categoria pelo id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Categoria"
      responses:
        202:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found" 
      security:
        - auth: []              
    delete:
      tags: 
        - deletar uma categoria
      summary: admin apaga uma categoria através do id
      responses:
        204:
          description: Sucesso
          content:
            application/json:
              example: "Categoria removida com sucesso"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found" 
      security:
        - auth: []               
    patch:
      tags:
      - alterando status categoria
      summary: admin altera status de uma categoria via id
      responses:
        201:
          description: Nova categoria criada com sucesso!
          content:
            application/json:
              example: "Categoria atualiza"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not found"
      security:
        - auth: []              
components:
  schemas:
    Categoria:
      type: object
      properties: 
        id:
          type: integer
        nome:
          type: string
        status: 
          type: string
      $ref: "#/components/schemas/Categoria"   
    Categoriaslista:
      type: array
      items: 
        $ref: "#/components/schemas/Categoria"
  securitySchemes:
    auth:   
      type: http
      scheme: bearer
      bearerFormat: JWT